DROP TABLE IF EXISTS journal_entries CASCADE;

CREATE TABLE journal_entries(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  tags TEXT [] DEFAULT NULL,
  date_created DATE NOT NULL DEFAULT CURRENT_DATE
);