DROP TABLE IF EXISTS tasks CASCADE;

CREATE TABLE tasks(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  description TEXT,
  status VARCHAR(255) NOT NULL DEFAULT 'todo',
  date_created DATE NOT NULL DEFAULT CURRENT_DATE
);